vich_uploader:
    db_driver: orm

    mappings:
        fromage_images:
            uri_prefix:         '%fromage_images%'
            upload_destination: '%kernel.project_dir%/public%fromage_images%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: true
            delete_on_remove: true
