<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBkMXQxl\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBkMXQxl/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerBkMXQxl.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerBkMXQxl\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerBkMXQxl\App_KernelProdContainer([
    'container.build_hash' => 'BkMXQxl',
    'container.build_id' => 'b730f7c6',
    'container.build_time' => 1673204509,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBkMXQxl');
