<?php

namespace ContainerBkMXQxl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEasyadminService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\EventSubscriber\Easyadmin' shared autowired service.
     *
     * @return \App\EventSubscriber\Easyadmin
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\EventSubscriber\\Easyadmin'] = new \App\EventSubscriber\Easyadmin(($container->privates['slugger'] ?? ($container->privates['slugger'] = new \Symfony\Component\String\Slugger\AsciiSlugger('fr'))), ($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')), ($container->services['.container.private.security.password_encoder'] ?? $container->load('get_Container_Private_Security_PasswordEncoderService')), ($container->services['.container.private.security.token_storage'] ?? $container->get_Container_Private_Security_TokenStorageService()));
    }
}
