<?php

namespace ContainerBkMXQxl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLaitRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\LaitRepository' shared autowired service.
     *
     * @return \App\Repository\LaitRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\LaitRepository'] = new \App\Repository\LaitRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
